[Softmax](#0)

In [2]:
import numpy as np

<a name ="0"></a>
# Softmax

In [7]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
t_image = np.array([[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]
                   ]
                  )
t_image.shape

(3, 2)

In [13]:
exp_image = np.exp(t_image)
exp_image/np.sum(exp_image,axis=1,keepdims=True)

array([[0.59494777, 0.40505223],
       [0.59358204, 0.40641796],
       [0.49283789, 0.50716211]])

# Vectorization

In [15]:
import time
x1 = [1,2,3,4]
x2 = [4,5,6,7]

In [18]:
dot = 0
for i in range(len(x1)):
    dot += x1[i]*x2[i]

In [20]:
dot

60

In [23]:
np.dot(x1,x2)

60

In [26]:
outer = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]

In [28]:
outer


array([[ 4.,  5.,  6.,  7.],
       [ 8., 10., 12., 14.],
       [12., 15., 18., 21.],
       [16., 20., 24., 28.]])

In [30]:
np.outer(x1,x2)

array([[ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [12, 15, 18, 21],
       [16, 20, 24, 28]])

In [33]:
multiply = np.zeros(len(x1))


In [35]:
for i in range(len(x1)):
    multiply[i] = x1[i] * x2[i]

In [36]:
multiply

array([ 4., 10., 18., 28.])

In [31]:
np.multiply(x1,x2)

array([ 4, 10, 18, 28])